var data = modelContainerHotelDetails.getData();
data.id = createBookingID();

console.log("DATA: ", data);

getCacheoListHotelsSelected();


setTimeout(function() {

    ModelData.Add(oListHotelsSelected, data);
    setCacheoListHotelsSelected();

    jQuery.sap.require("sap.m.MessageBox");
    sap.m.MessageBox.show("Hotel added to your booking trip");

    oApp.backDetailToPage(MessagePage);
    oApp.backMasterToPage(oPageSearch);

}, 1000);